<?php

/**
 * @file
 * Imports seed/content.json (generated by the frontend's
 * scripts/export-content.mjs) into Drupal nodes.
 *
 * Remote images are downloaded into Drupal's file system rather than
 * hotlinked, so editors can swap them out later and the site stops depending
 * on Unsplash and the old WordPress install staying up.
 *
 * Idempotent — a node is matched by bundle + title (or slug where there is
 * one) and updated rather than duplicated, so this can be re-run safely.
 *
 *   drush php:script scripts/seed-content.php
 */

use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;

$path = __DIR__ . '/../seed/content.json';
if (!file_exists($path)) {
  echo "Missing $path — run `node scripts/export-content.mjs` in the frontend repo first.\n";
  return;
}
$data = json_decode(file_get_contents($path), TRUE);

$entityTypeManager = \Drupal::entityTypeManager();
$nodeStorage = $entityTypeManager->getStorage('node');
$termStorage = $entityTypeManager->getStorage('taxonomy_term');
$fileSystem = \Drupal::service('file_system');
$httpClient = \Drupal::httpClient();

$stats = ['created' => 0, 'updated' => 0, 'images' => 0, 'imageFailed' => 0];

/** Finds or creates a taxonomy term, returning its id. */
$term = function (string $vid, string $name) use ($termStorage): ?int {
  $name = trim($name);
  if ($name === '') {
    return NULL;
  }
  $existing = $termStorage->loadByProperties(['vid' => $vid, 'name' => $name]);
  if ($existing) {
    return (int) reset($existing)->id();
  }
  $new = Term::create(['vid' => $vid, 'name' => $name]);
  $new->save();
  return (int) $new->id();
};

/**
 * Registers a file shipped in seed/gallery/ and returns its file id.
 *
 * Gallery media is committed to this repo rather than downloaded, so unlike
 * $image() there is no network involved — the file is copied into Drupal's
 * public files and registered once. Re-runs find the existing record and reuse
 * it instead of copying again.
 */
$localFile = function (string $filename) use ($fileSystem, &$stats): ?int {
  if ($filename === '') {
    return NULL;
  }
  $source = __DIR__ . '/../seed/gallery/' . $filename;
  if (!file_exists($source)) {
    echo "  ! missing gallery file: $filename\n";
    $stats['imageFailed']++;
    return NULL;
  }

  $directory = 'public://gallery';
  $destination = "$directory/$filename";

  $existing = \Drupal::entityTypeManager()->getStorage('file')
    ->loadByProperties(['uri' => $destination]);
  if ($existing) {
    return (int) reset($existing)->id();
  }

  $fileSystem->prepareDirectory($directory, \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY);
  $fileSystem->saveData(file_get_contents($source), $destination, \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE);
  $file = File::create(['uri' => $destination, 'status' => 1]);
  $file->save();
  $stats['images']++;
  return (int) $file->id();
};

/**
 * Returns a file id for an image reference.
 *
 * Absolute URLs are downloaded once and cached. Anything else is treated as a
 * file shipped in seed/gallery/ — video thumbnails, for instance, are stored
 * with the repo rather than fetched, and arrive here as a path like
 * "/videos/abc.jpg". Without this they were handed to the HTTP client, which
 * failed on every one and left those nodes with no image at all.
 */
$image = function (string $url) use ($httpClient, $fileSystem, &$stats, &$localFile): ?int {
  if ($url === '') {
    return NULL;
  }
  if (!preg_match('#^https?://#i', $url)) {
    return $localFile(basename($url));
  }
  // A stable filename keyed on the URL means re-runs reuse the same file
  // instead of downloading it again.
  $extension = pathinfo(parse_url($url, PHP_URL_PATH) ?: '', PATHINFO_EXTENSION);
  $extension = preg_match('/^(jpg|jpeg|png|webp|gif)$/i', $extension) ? strtolower($extension) : 'jpg';
  $name = substr(hash('sha256', $url), 0, 16) . '.' . $extension;
  $directory = 'public://seed-images';
  $destination = "$directory/$name";

  $existing = \Drupal::entityTypeManager()->getStorage('file')
    ->loadByProperties(['uri' => $destination]);
  if ($existing) {
    return (int) reset($existing)->id();
  }

  $fileSystem->prepareDirectory($directory, \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY);
  try {
    $bytes = $httpClient->get($url, ['timeout' => 30])->getBody()->getContents();
  }
  catch (\Throwable $e) {
    echo "  ! image failed: $url ({$e->getMessage()})\n";
    $stats['imageFailed']++;
    return NULL;
  }
  $fileSystem->saveData($bytes, $destination, \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE);
  $file = File::create(['uri' => $destination, 'status' => 1]);
  $file->save();
  $stats['images']++;
  return (int) $file->id();
};

/**
 * Node ids this run created or updated, keyed by bundle. Used by the prune step
 * at the bottom to spot leftovers from earlier seeds.
 */
$touched = [];

/** Creates or updates one node, matching on slug when the bundle has one. */
$upsert = function (string $bundle, string $title, array $fields, ?string $slug = NULL)
    use ($nodeStorage, &$stats, &$touched): void {
  $properties = ['type' => $bundle];
  if ($slug !== NULL) {
    $properties['field_slug'] = $slug;
  }
  else {
    $properties['title'] = $title;
  }
  $existing = $nodeStorage->loadByProperties($properties);

  if ($existing) {
    $node = reset($existing);
    $stats['updated']++;
  }
  else {
    $node = Node::create(['type' => $bundle]);
    $stats['created']++;
  }

  $node->set('title', $title);
  $node->set('status', 1);
  foreach ($fields as $name => $value) {
    if ($value !== NULL) {
      $node->set($name, $value);
    }
  }
  $node->save();
  $touched[$bundle][] = (int) $node->id();
};

foreach ($data['heroStats'] as $i => $s) {
  $upsert('hero_stat', $s['label'], [
    'field_end' => $s['end'],
    'field_suffix' => $s['suffix'],
    'field_divisor' => $s['divisor'],
    'field_decimals' => $s['decimals'],
    'field_weight' => $i,
  ]);
}

foreach ($data['services'] as $i => $s) {
  $upsert('service', $s['title'], [
    'field_slug' => $s['slug'],
    'field_icon' => $s['icon'],
    'field_accent' => $s['accent'],
    'field_desc' => $s['desc'],
    'field_body' => $s['body'],
    'field_weight' => $i,
  ], $s['slug']);
}

foreach ($data['partners'] as $p) {
  $upsert('partner', $p['name'], ['field_weight' => $p['weight']]);
}

foreach ($data['impactCards'] as $c) {
  $upsert('impact_card', $c['label'], [
    'field_icon' => $c['icon'],
    'field_value' => $c['value'],
    'field_sub' => $c['sub'],
    'field_weight' => $c['weight'],
  ]);
}

foreach ($data['countries'] as $i => $c) {
  $upsert('country', $c['country'], [
    'field_lon' => $c['lon'],
    'field_lat' => $c['lat'],
    'field_weight' => $i,
  ]);
}

foreach ($data['pageHeroes'] as $i => $h) {
  // A page hero may legitimately carry no display title — the "team" entry
  // exists only to hold an intro line the frontend hides while it is blank.
  // Drupal still needs a node title, so fall back to the slug as an admin
  // label; the frontend reads field_slug and the other fields, never this.
  $title = trim((string) $h['title']) !== '' ? $h['title'] : $h['slug'];
  $upsert('page_hero', $title, [
    'field_slug' => $h['slug'],
    'field_eyebrow' => $h['eyebrow'],
    'field_subtitle' => $h['subtitle'],
    'field_weight' => $i,
  ], $h['slug']);
}

foreach ($data['gallery'] as $g) {
  $upsert('gallery_item', $g['title'], [
    'field_slug' => $g['slug'],
    'field_media_type' => $g['type'],
    'field_media' => $localFile($g['src']),
    'field_poster' => $localFile($g['poster']),
    'field_caption' => $g['caption'],
    'field_featured' => $g['featured'] ? 1 : 0,
    'field_weight' => $g['weight'],
  ], $g['slug']);
}

// TerraFund champion organisations — photo, description, website and targets
// from TerraFund's published "Meet the Champions" profiles.
//
// Projects belong to staff once seeded: they add new ones and edit existing
// ones in Drupal (see the project form set up by add-project-fields.php), so a
// routine deploy must not overwrite any of that. This block therefore only
// runs when content.json carries a higher projectsSeedVersion than this
// environment has already applied — bump PROJECTS_SEED_VERSION in the
// frontend's export-content.mjs when data.ts has a portfolio update that
// should replace what's in Drupal. `project` is also not in $prunable below,
// so a project added by hand is never deleted as "stale".
//
// Even when it runs, field_*_done is only written when data.ts carries a
// value, so real delivery figures entered in Drupal are never blanked.
$projectsVersion = (int) ($data['projectsSeedVersion'] ?? 1);
$projectsApplied = (int) \Drupal::state()->get('via_seed.projects_version', 0);
if ($projectsVersion > $projectsApplied) {
  foreach ($data['projects'] as $i => $p) {
    $done = [];
    foreach (['treesDone' => 'field_trees_done', 'hectaresDone' => 'field_hectares_done', 'jobsDone' => 'field_jobs_done'] as $key => $field) {
      if (($p[$key] ?? '') !== '') {
        $done[$field] = $p[$key];
      }
    }

    $upsert('project', $p['name'], [
      'field_slug' => $p['slug'],
      'field_country_ref' => $term('project_country', $p['country']),
      'field_cohort' => $p['cohort'],
      'field_org_type' => $p['orgType'],
      'field_organisation_type' => $p['orgType'],
      'field_trees' => $p['trees'],
      'field_hectares' => $p['hectares'],
      'field_jobs' => $p['jobs'],
      'field_website' => $p['website'],
      'field_excerpt' => $p['excerpt'],
      'field_image' => ($p['image'] ?? '') !== '' ? $localFile($p['image']) : NULL,
      'field_weight' => $i,
    ] + $done, $p['slug']);
  }
  \Drupal::state()->set('via_seed.projects_version', $projectsVersion);
  echo "  projects: applied seed version $projectsVersion\n";
}
else {
  echo "  projects: seed version $projectsVersion already applied, left as staff have them\n";
}

foreach ($data['stories'] as $i => $s) {
  $upsert('story', $s['title'], [
    'field_slug' => $s['slug'],
    'field_image' => $image($s['image']),
    // [] rather than NULL, so a story whose category was removed is actually
    // cleared — $upsert() skips NULLs.
    'field_category' => $term('story_category', $s['category']) ?? [],
    'field_date_label' => $s['date'],
    'field_featured' => $s['featured'] ? 1 : 0,
    'field_excerpt' => $s['excerpt'],
    'field_body' => $s['body'],
    'field_youtube_id' => $s['youtubeId'] ?? '',
    'field_published_at' => $s['publishedAt'] ?? '',
    'field_duration' => $s['duration'] ?? '',
    'field_weight' => $i,
  ], $s['slug']);
}

// Stories are one category on the merged News page, film or written, so the
// separate "Videos" story category is gone. Its term is removed once nothing
// uses it any more (a story staff still have filed under it keeps it alive).
foreach ($termStorage->loadByProperties(['vid' => 'story_category', 'name' => 'Videos']) as $videos) {
  $inUse = $nodeStorage->getQuery()->accessCheck(FALSE)->condition('type', 'story')->condition('field_category', $videos->id())->count()->execute();
  if (!$inUse) {
    $videos->delete();
    echo "  removed unused story category \"Videos\"\n";
  }
}

foreach ($data['news'] as $i => $n) {
  $upsert('news', $n['title'], [
    'field_slug' => $n['slug'],
    'field_image' => $image($n['image']),
    'field_category' => $term('news_category', $n['category']),
    'field_date_label' => $n['date'],
    'field_body' => $n['body'],
    'field_weight' => $i,
  ], $n['slug']);
}

foreach ($data['team'] as $m) {
  $upsert('team_member', $m['name'], [
    'field_role' => $m['role'],
    'field_location' => $m['location'],
    'field_featured' => $m['featured'] ? 1 : 0,
    'field_bio' => $m['bio'],
    'field_image' => $image($m['image']),
    'field_weight' => $m['weight'],
  ]);
}

// Home page before/after strip. field_image reuses the same local files as
// gallery — $localFile() looks in seed/gallery/ either way.
foreach ($data['restorationTimeline'] as $r) {
  $upsert('restoration_photo', $r['alt'], [
    'field_slug' => $r['slug'],
    'field_image' => $localFile($r['image']),
    'field_year' => $r['year'],
    'field_weight' => $r['weight'],
  ], $r['slug']);
}

// Every News category the frontend knows about, so a category with nothing
// tagged yet (Documentation, before its first upload) still exists to filter
// by. $term() only ever creates what's missing.
foreach ($data['newsCategories'] ?? [] as $name) {
  $term('news_category', $name);
}

/**
 * About page: vision/mission statements, pillars and donors.
 *
 * These are staff-owned. content.json only provides the starting content, so
 * each bundle is seeded once — when it has no nodes at all — and never touched
 * again: a donor added, reworded or deleted in Drupal survives every later
 * deploy. They are deliberately not in $prunable below for the same reason.
 * To reset one to the seed, delete all of its nodes in Drupal and reseed.
 */
$seedOnce = function (string $bundle, array $rows, callable $build) use ($nodeStorage, $upsert): void {
  if (!$rows || $nodeStorage->getQuery()->accessCheck(FALSE)->condition('type', $bundle)->count()->execute() > 0) {
    return;
  }
  foreach ($rows as $i => $row) {
    [$title, $fields] = $build($row);
    $upsert($bundle, $title, $fields + ['field_weight' => $i]);
  }
};

$seedOnce('purpose_statement', $data['purpose'] ?? [], fn($p) => [$p['title'], [
  'field_kicker' => $p['kicker'],
  'field_desc' => $p['body'],
]]);

$seedOnce('pillar', $data['pillars'] ?? [], fn($p) => [$p['title'], [
  'field_desc' => $p['desc'],
]]);

$seedOnce('donor', $data['donors'] ?? [], fn($d) => [$d['name'], [
  'field_image' => $localFile($d['logo']),
  'field_website' => $d['website'],
]]);

/**
 * Upserting alone can only ever add. Renaming a hero stat or dropping a partner
 * from content.json leaves the old node behind, still published, still in the
 * API response — so the site shows both the old and the new.
 *
 * These bundles are generated wholly from content.json, so anything this run did
 * not touch is a leftover and safe to remove. `project` used to be here too;
 * it no longer is, because staff now add projects directly in Drupal.
 *
 * The bundles editors author directly (news, story, team_member, service,
 * testimonial) are deliberately excluded: a Careers vacancy written in Drupal
 * must survive a reseed.
 *
 * Reports by default; deletes only when asked:
 *   SEED_PRUNE=1 drush php:script scripts/seed-content.php
 */
$prunable = ['hero_stat', 'impact_card', 'partner', 'country', 'funding_allocation', 'yearly_progress', 'page_hero', 'gallery_item', 'restoration_photo'];
$prune = getenv('SEED_PRUNE') === '1';
$stale = [];

foreach ($prunable as $bundle) {
  $all = $nodeStorage->loadByProperties(['type' => $bundle]);
  foreach ($all as $nid => $node) {
    if (!in_array((int) $nid, $touched[$bundle] ?? [], TRUE)) {
      $stale[] = [$bundle, (int) $nid, $node->label()];
    }
  }
}

echo "Seed complete.\n";
foreach ($stats as $what => $n) {
  echo sprintf("  %-12s %d\n", $what . ':', $n);
}

if (!$stale) {
  echo "  no stale nodes\n";
}
elseif ($prune) {
  foreach ($stale as [$bundle, $nid, $label]) {
    $nodeStorage->load($nid)->delete();
    echo "  deleted  $bundle #$nid \"$label\"\n";
  }
  echo sprintf("  pruned:      %d\n", count($stale));
}
else {
  echo sprintf("\n%d stale node(s) left over from an earlier seed:\n", count($stale));
  foreach ($stale as [$bundle, $nid, $label]) {
    echo "  $bundle #$nid \"$label\"\n";
  }
  echo "\nRe-run with SEED_PRUNE=1 to delete them.\n";
}
