<?php

/**
 * @file
 * Imports seed/content.json (generated by the frontend's
 * scripts/export-content.mjs) into Drupal nodes.
 *
 * Remote images are downloaded into Drupal's file system rather than
 * hotlinked, so editors can swap them out later and the site stops depending
 * on Unsplash and the old WordPress install staying up.
 *
 * Idempotent — a node is matched by bundle + title (or slug where there is
 * one) and updated rather than duplicated, so this can be re-run safely.
 *
 *   drush php:script scripts/seed-content.php
 */

use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;

$path = __DIR__ . '/../seed/content.json';
if (!file_exists($path)) {
  echo "Missing $path — run `node scripts/export-content.mjs` in the frontend repo first.\n";
  return;
}
$data = json_decode(file_get_contents($path), TRUE);

$entityTypeManager = \Drupal::entityTypeManager();
$nodeStorage = $entityTypeManager->getStorage('node');
$termStorage = $entityTypeManager->getStorage('taxonomy_term');
$fileSystem = \Drupal::service('file_system');
$httpClient = \Drupal::httpClient();

$stats = ['created' => 0, 'updated' => 0, 'images' => 0, 'imageFailed' => 0];

/** Finds or creates a taxonomy term, returning its id. */
$term = function (string $vid, string $name) use ($termStorage): ?int {
  $name = trim($name);
  if ($name === '') {
    return NULL;
  }
  $existing = $termStorage->loadByProperties(['vid' => $vid, 'name' => $name]);
  if ($existing) {
    return (int) reset($existing)->id();
  }
  $new = Term::create(['vid' => $vid, 'name' => $name]);
  $new->save();
  return (int) $new->id();
};

/** Downloads a remote image once and returns a file id. */
$image = function (string $url) use ($httpClient, $fileSystem, &$stats): ?int {
  if ($url === '') {
    return NULL;
  }
  // A stable filename keyed on the URL means re-runs reuse the same file
  // instead of downloading it again.
  $extension = pathinfo(parse_url($url, PHP_URL_PATH) ?: '', PATHINFO_EXTENSION);
  $extension = preg_match('/^(jpg|jpeg|png|webp|gif)$/i', $extension) ? strtolower($extension) : 'jpg';
  $name = substr(hash('sha256', $url), 0, 16) . '.' . $extension;
  $directory = 'public://seed-images';
  $destination = "$directory/$name";

  $existing = \Drupal::entityTypeManager()->getStorage('file')
    ->loadByProperties(['uri' => $destination]);
  if ($existing) {
    return (int) reset($existing)->id();
  }

  $fileSystem->prepareDirectory($directory, \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY);
  try {
    $bytes = $httpClient->get($url, ['timeout' => 30])->getBody()->getContents();
  }
  catch (\Throwable $e) {
    echo "  ! image failed: $url ({$e->getMessage()})\n";
    $stats['imageFailed']++;
    return NULL;
  }
  $fileSystem->saveData($bytes, $destination, \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE);
  $file = File::create(['uri' => $destination, 'status' => 1]);
  $file->save();
  $stats['images']++;
  return (int) $file->id();
};

/**
 * Node ids this run created or updated, keyed by bundle. Used by the prune step
 * at the bottom to spot leftovers from earlier seeds.
 */
$touched = [];

/** Creates or updates one node, matching on slug when the bundle has one. */
$upsert = function (string $bundle, string $title, array $fields, ?string $slug = NULL)
    use ($nodeStorage, &$stats, &$touched): void {
  $properties = ['type' => $bundle];
  if ($slug !== NULL) {
    $properties['field_slug'] = $slug;
  }
  else {
    $properties['title'] = $title;
  }
  $existing = $nodeStorage->loadByProperties($properties);

  if ($existing) {
    $node = reset($existing);
    $stats['updated']++;
  }
  else {
    $node = Node::create(['type' => $bundle]);
    $stats['created']++;
  }

  $node->set('title', $title);
  $node->set('status', 1);
  foreach ($fields as $name => $value) {
    if ($value !== NULL) {
      $node->set($name, $value);
    }
  }
  $node->save();
  $touched[$bundle][] = (int) $node->id();
};

foreach ($data['heroStats'] as $i => $s) {
  $upsert('hero_stat', $s['label'], [
    'field_end' => $s['end'],
    'field_suffix' => $s['suffix'],
    'field_divisor' => $s['divisor'],
    'field_decimals' => $s['decimals'],
    'field_weight' => $i,
  ]);
}

foreach ($data['services'] as $i => $s) {
  $upsert('service', $s['title'], [
    'field_slug' => $s['slug'],
    'field_icon' => $s['icon'],
    'field_accent' => $s['accent'],
    'field_desc' => $s['desc'],
    'field_body' => $s['body'],
    'field_weight' => $i,
  ], $s['slug']);
}

foreach ($data['partners'] as $p) {
  $upsert('partner', $p['name'], ['field_weight' => $p['weight']]);
}

foreach ($data['impactCards'] as $c) {
  $upsert('impact_card', $c['label'], [
    'field_icon' => $c['icon'],
    'field_value' => $c['value'],
    'field_sub' => $c['sub'],
    'field_weight' => $c['weight'],
  ]);
}

foreach ($data['countries'] as $i => $c) {
  $upsert('country', $c['country'], [
    'field_lon' => $c['lon'],
    'field_lat' => $c['lat'],
    'field_weight' => $i,
  ]);
}

// TerraFund champion organisations. The superseded fields (funding, funder,
// status, communities, progress, result, image, category, body) still exist on
// the bundle with their old content, but nothing reads them any more — see
// scripts/add-project-fields.php.
foreach ($data['projects'] as $i => $p) {
  $upsert('project', $p['name'], [
    'field_slug' => $p['slug'],
    'field_country_ref' => $term('project_country', $p['country']),
    'field_cohort' => $p['cohort'],
    'field_org_type' => $p['orgType'],
    'field_trees' => $p['trees'],
    'field_hectares' => $p['hectares'],
    'field_jobs' => $p['jobs'],
    'field_website' => $p['website'],
    'field_excerpt' => $p['excerpt'],
    'field_weight' => $i,
  ], $p['slug']);
}

foreach ($data['stories'] as $i => $s) {
  $upsert('story', $s['title'], [
    'field_slug' => $s['slug'],
    'field_image' => $image($s['image']),
    'field_category' => $term('story_category', $s['category']),
    'field_date_label' => $s['date'],
    'field_featured' => $s['featured'] ? 1 : 0,
    'field_excerpt' => $s['excerpt'],
    'field_body' => $s['body'],
    'field_weight' => $i,
  ], $s['slug']);
}

foreach ($data['news'] as $i => $n) {
  $upsert('news', $n['title'], [
    'field_slug' => $n['slug'],
    'field_image' => $image($n['image']),
    'field_category' => $term('news_category', $n['category']),
    'field_date_label' => $n['date'],
    'field_body' => $n['body'],
    'field_weight' => $i,
  ], $n['slug']);
}

foreach ($data['team'] as $m) {
  $upsert('team_member', $m['name'], [
    'field_role' => $m['role'],
    'field_location' => $m['location'],
    'field_featured' => $m['featured'] ? 1 : 0,
    'field_bio' => $m['bio'],
    'field_image' => $image($m['image']),
    'field_weight' => $m['weight'],
  ]);
}

/**
 * Upserting alone can only ever add. Renaming a hero stat or dropping a partner
 * from content.json leaves the old node behind, still published, still in the
 * API response — so the site shows both the old and the new.
 *
 * These bundles are generated wholly from content.json, so anything this run did
 * not touch is a leftover and safe to remove. `project` is on the list because
 * the portfolio is generated in full from the TerraFund export — a project not
 * in that export is not a project VIA supports.
 *
 * The bundles editors author directly (news, story, team_member, service,
 * testimonial) are deliberately excluded: a Careers vacancy written in Drupal
 * must survive a reseed.
 *
 * Reports by default; deletes only when asked:
 *   SEED_PRUNE=1 drush php:script scripts/seed-content.php
 */
$prunable = ['hero_stat', 'impact_card', 'partner', 'country', 'funding_allocation', 'yearly_progress', 'project'];
$prune = getenv('SEED_PRUNE') === '1';
$stale = [];

foreach ($prunable as $bundle) {
  $all = $nodeStorage->loadByProperties(['type' => $bundle]);
  foreach ($all as $nid => $node) {
    if (!in_array((int) $nid, $touched[$bundle] ?? [], TRUE)) {
      $stale[] = [$bundle, (int) $nid, $node->label()];
    }
  }
}

echo "Seed complete.\n";
foreach ($stats as $what => $n) {
  echo sprintf("  %-12s %d\n", $what . ':', $n);
}

if (!$stale) {
  echo "  no stale nodes\n";
}
elseif ($prune) {
  foreach ($stale as [$bundle, $nid, $label]) {
    $nodeStorage->load($nid)->delete();
    echo "  deleted  $bundle #$nid \"$label\"\n";
  }
  echo sprintf("  pruned:      %d\n", count($stale));
}
else {
  echo sprintf("\n%d stale node(s) left over from an earlier seed:\n", count($stale));
  foreach ($stale as [$bundle, $nid, $label]) {
    echo "  $bundle #$nid \"$label\"\n";
  }
  echo "\nRe-run with SEED_PRUNE=1 to delete them.\n";
}
